### PR TITLE
Fixes #896 : Fixed getVertexCount() method issue of giving output 0 for GROUP shapes

### LINKED ISSUE #896: PShape.getVertexCount() always outputs 0
### Most appropriate sub-area of Processing 4?

Core/Environment/Rendering

### Processing version

4.3.1

### Operating system

Windows 11 (24H2)

### Steps to reproduce this

`PShape.getVertexCount()` always seems to output 0. (tried 1 .svg file and 4 .obj files, even included the .mtl files)

### snippet

```processing
PShape shape;
  
void setup() {
  size(640, 360, P3D);
    
  shape = loadShape("cuboctahedron.obj");
  println(shape.getVertexCount()); // zero???
}

void draw() {
  background(0);
  lights();
  translate(width/2, height/2, -200);
  scale(50);
  rotateY((float)millis()/2000);
  shape(shape);
}
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by inteqam**
Fixed the issue of getting output 0 from `getVertexCount()` method for `GROUP` shapes by Updating the `getVertexCount()` method in `PShape` class and `PShapeOpenGL` class

Closes #896

### CODE REVIEW

**Review by Stefterv — CHANGES_REQUESTED** [review]
Thank you @inteqam for your contribution, as this code change will impact functionality of existing sketches (see discussion in #896) will have to make some changes still, but it's a great effort!

File: core/src/processing/core/PShape.java [hunk 1]
```diff
@@ -2345,8 +2345,18 @@ protected void setPath(int vcount, float[][] verts, int ccount, int[] codes) {
    * @see PShape#getVertex(int)
    * @see PShape#setVertex(int, float, float)
    */
+  public int getVertexCount(boolean includeChildren) {
```
Comment (Stefterv) [inline core/src/processing/core/PShape.java:2348]: Last thing to add, update the Javadoc comment above

**Review by Stefterv — CHANGES_REQUESTED** [review]
Thank you for the quick updates @inteqam! Looking great, just one more small thing to fix :)

**Review by Stefterv — APPROVED** [review]

**Comment by inteqam** [comment]
@Stefterv I appreciate your help on working through this issue :)

**Comment by SableRaf** [comment]
Merged! Thanks for your contribution @inteqam 💙

**Comment by SableRaf** [comment]
@all-contributors add @inteqam for code
