### PR TITLE
Display Welcome to Beta once per revision

### LINKED ISSUE #1198: Disable beta welcome message
### Most appropriate sub-area of Processing 4?

Accessibility, Other (specify if possible)

### Processing version

4.4.76

### Operating system

Windows

### Bug description

There's currently no obvious way to disable the Welcome to Beta message every time you open the application.

Adding these flags in the preferences.txt file has no effect:
`beta.disable_welcome=true`
`beta.welcome.dismissed=true`
`beta.welcome.shown=true`

Image

### Steps to reproduce this

"1. Install the 4.4.76 Beta

2. Open the program

3. Click the OK button everytime"

### Additional context

_No response_

### Would you like to work on the issue?

No, I’m just reporting the issue

### PR DESCRIPTION
**Pull request by catilac**
Limits the Welcome to Beta screen to once per downloaded revision.

Closes #1198

### CODE REVIEW

File: app/src/processing/app/UpdateCheck.java [hunk 1]
```diff
@@ -135,8 +135,20 @@ public void updateCheck() throws IOException {
...
+      String lastBetaSeenStr = Preferences.get("beta.last_beta_welcome_seen");
+      int lastBetaSeen = 0;
+      if (lastBetaSeenStr != null) {
+          lastBetaSeen = Integer.parseInt(lastBetaSeenStr);
+      }
+      int revision = Base.getRevision();
+      System.err.println("MOON DEBUG" +
+              Base.getRevision() + ", and lastBetaSeen is " +
+              lastBetaSeen + ".");
+
```
Comment (catilac) [inline app/src/processing/app/UpdateCheck.java]: will remove this, i suppose

File: app/src/processing/app/ui/WelcomeToBeta.kt [hunk 2]
```diff
@@ -61,7 +62,10 @@ class WelcomeToBeta {
             val mac = SystemInfo.isMacFullWindowContentSupported
             SwingUtilities.invokeLater {
                 JFrame(windowTitle).apply {
-                    val close = { dispose() }
+                    val close = {
+                       Preferences.set("beta.last_beta_welcome_seen", getRevision().toString())
```
Comment (catilac) [inline app/src/processing/app/ui/WelcomeToBeta.kt]: i need a better key name. wondering your thoughts. should it be `update.beta_welcome` or something?

Comment (Stefterv) [reply app/src/processing/app/ui/WelcomeToBeta.kt]: `update.beta_prompt`

File: app/src/processing/app/UpdateCheck.java [hunk 3]
```diff
@@ -135,8 +135,20 @@ public void updateCheck() throws IOException {
 //        offerToUpdateContributions = !promptToVisitDownloadPage();
         promptToVisitDownloadPage();
       }
-      if(latest < Base.getRevision()){
-        WelcomeToBeta.showWelcomeToBeta();
+
+      String lastBetaSeenStr = Preferences.get("beta.last_beta_welcome_seen");
```
Comment (Stefterv) [inline app/src/processing/app/UpdateCheck.java]: I would say using `Preferences.getInteger()` would be a better choice here, to make sure it is never empty you can add the key to the `defaults.txt` in `build/shared/lib/defaults.txt`

File: app/src/processing/app/UpdateCheck.java (hunk 1 above)
Comment (Stefterv) [reply app/src/processing/app/UpdateCheck.java]: Yep, feel free to use `Messages.log` that will be hidden for users and will give us valuable information when looking at the logs

**Review by Stefterv — APPROVED** [review]

**Review by SableRaf — APPROVED** [review]

**Comment by SableRaf** [comment]
@all-contributors please add @catilac for code
