### PR TITLE
fix(cli): support sketches with custom main file names

### LINKED ISSUE #1219: `processing cli` does not support sketches with a different `main.pde` file
### Most appropriate sub-area of Processing 4?

PDE

### Processing version

4.4.6

### Operating system

macOS

### Bug description

When running the Processing cli, having a sketch with a different main file, e.g. `sketch/main.pde` the cli returns that the sketch is not a valid sketch folder, `sketch/sketch.pde` does not exist. 

### Steps to reproduce this

1. Create a new sketch

2. Rename the main file 

3. Try to run the sketch with the cli

### snippet

_No response_

### Additional context

_No response_

### Would you like to work on the issue?

No, I’m just reporting the issue

### PR DESCRIPTION
**Pull request by avinxshKD**
## Problem
CLI rejected sketches with custom main file names (e.g., `sketch/main.pde`) even though the IDE supports them via `sketch.properties`.

## Solution
Updated CLI to check `sketch.properties` for a `main` property before falling back to default naming, matching IDE behavior from `Sketch.findMain()`.

## Changes
- `Commander.java`: Added Settings import and custom main file detection logic
- `CommanderTest.java`: Added unit tests for default and custom main file handling

Fixes #1219

### CODE REVIEW

File: java/src/processing/mode/java/Commander.java [hunk 1]
```diff
@@ -145,7 +146,24 @@ public Commander(String[] args) {
...
+          // sketch.properties doesn't exist or couldn't be read, will use default
+        }
+        
+        // Fall back to default naming convention if no custom main file specified
+        if (pdeFile == null || !pdeFile.exists()) {
+          pdeFile = new File(sketchFolder, sketchFolder.getName() + ".pde");
+        }
+        
         if (!pdeFile.exists()) {
           complainAndQuit("Not a valid sketch folder. " + pdeFile + " does not exist.", true);
```
Comment (SableRaf) [inline java/src/processing/mode/java/Commander.java]: @Stefterv Maybe instead of rejecting the folder when folderName.pde is missing, the CLI could handle the following two two cases:

1.	Opening a folder with multiple .pde files but no explicit main file: ask the user whether they want to rename the folder OR choose which .pde should act as the main one, then generate sketch.properties accordingly.
	
2.	Opening a single .pde file inside a folder without an explicit main file: treat that file as the main one and create sketch.properties to match.

That would be closer to the PDE’s behavior. What do you think?

**Comment by avinxshKD** [comment]
@Stefterv, kindly review this too when you get a chance

**Comment by Stefterv** [comment]
Hi @avinxshKD the code looks great to me, the tests however could use some work. Could you please create a test that tests the actual issue? See https://github.com/processing/processing4/blob/main/app/test/processing/app/CLITest.kt on how to write tests for the Command Line Interface!

**Comment by avinxshKD** [comment]
> Hi @avinxshKD the code looks great to me, the tests however could use some work. Could you please create a test that tests the actual issue? See https://github.com/processing/processing4/blob/main/app/test/processing/app/CLITest.kt on how to write tests for the Command Line Interface!

Hi @Stefterv, thank you for the feedback! I've made the following updates:

1. **Added CLI test** to `CLITest.kt` as requested - `testSketchWithCustomMainFile()` follows the same pattern as existing tests and provides instructions for manual testing in IntelliJ IDEA.

The CLI test is ready for manual verification once you have a chance to test with a sketch that has a custom main file in `sketch.properties`.

**Comment by Stefterv** [comment]
Hi @avinxshKD please see here on how to create a temporary directory and temporary sketch so this does not need to be a manual test. We do not do any manual testing unfortunately 
https://github.com/processing/processing4/blob/ef226c9ec6e4d5ead59ed2912516397b7e766ca3/app/test/processing/app/SketchbookTest.kt#L16-L23

**Comment by avinxshKD** [comment]
Hi @Stefterv, thank you for the guidance  I've updated the test to be fully automated as requested

**Comment by avinxshKD** [comment]
@Stefterv Hey, pls review and is there anything you think I should add or improve? If yes, I’ll work on it after my exams. Thanks

**Review by catilac — APPROVED** [review]

**Comment by SableRaf** [comment]
@all-contributors please add @avinxshKD for code

**Comment by SableRaf** [comment]
@catilac should I open a new issue for the following review item?

https://github.com/processing/processing4/pull/1329#discussion_r2539752342
